@startuml
'https://plantuml.com/sequence-diagram
Class Adherent{
    -numeroAdherent : int
    -prenomAdherent : string
    -nomAdherent : string
    -emailAdherent : string
    -dateAdhesion : Date
    +genererNumero()
    +renouvelerAdhesion()
    +informationsAdherent()
    +adhesionValable()

}
Abstract Class Media{
    #titre : string
    #dureeEmpruntMax
    +presenter()
}
Class BlueRay{
    -realisateur : string
    -duree minutes : int
    -anneeSortie:int

    +presenter()

}

Class Livre{
    -isbn : string
    -auteur:string
    -nbPages:int

    +presenter()

}

Class Magazine{
    -numero : int
    -datePublication : Date

    +presenter()

}

Class Emprunt{
    -dateEmprunt : Date
    -dateRetourEstimee: Date
    -dateRetour: Date
    +informationEmprunt()
    +verifierEmprunt()
    +verifierAlerteEmprunt()
    +verifierDureeAutorisee()
}
Media <|-- Livre
Media <|-- BlueRay
Media <|-- Magazine

Emprunt  --> "1..1" Media : Un media est emprunté
Emprunt --> "1..1" Adherent : Un emprunt est réalisé par un adhérent


@enduml